apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: vpnaas
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: vpnaas
data:
  vpnaas-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "VPNaaS Dashboard",
        "tags": ["vpnaas"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Total Users",
            "type": "stat",
            "targets": [
              {
                "expr": "vpnaas_total_users",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "displayMode": "list"
                }
              }
            }
          },
          {
            "id": 2,
            "title": "Active Users",
            "type": "stat",
            "targets": [
              {
                "expr": "vpnaas_active_users",
                "refId": "A"
              }
            ]
          },
          {
            "id": 3,
            "title": "VPN Pods Status",
            "type": "piechart",
            "targets": [
              {
                "expr": "vpnaas_vpn_pods_running",
                "legendFormat": "Running",
                "refId": "A"
              },
              {
                "expr": "vpnaas_vpn_pods_failed",
                "legendFormat": "Failed",
                "refId": "B"
              },
              {
                "expr": "vpnaas_vpn_pods_pending",
                "legendFormat": "Pending",
                "refId": "C"
              }
            ]
          },
          {
            "id": 4,
            "title": "Total Connections",
            "type": "stat",
            "targets": [
              {
                "expr": "vpnaas_total_connections",
                "refId": "A"
              }
            ]
          },
          {
            "id": 5,
            "title": "Data Usage",
            "type": "stat",
            "targets": [
              {
                "expr": "vpnaas_total_data_usage_bytes",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "bytes"
              }
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "5s"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: vpnaas
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: vpnaas
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP
